language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7

before_script:
  - composer self-update
  - composer update --working-dir=./build-advisories

script:
  - ./build-advisories/vendor/bin/phpunit -c build-advisories
  - php ./build-advisories/build-conflicts.php
